package memory

import (
	"testing"
	"time"
)

func TestProjectOverview_GetEmpty(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Get overview from fresh DB should return nil, no error
	overview, err := db.GetProjectOverview()
	if err != nil {
		t.Fatalf("GetProjectOverview failed: %v", err)
	}
	if overview != nil {
		t.Errorf("expected nil overview on fresh DB, got %+v", overview)
	}
}

func TestProjectOverview_SaveAndGet(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Create an overview
	now := time.Now().UTC().Truncate(time.Second)
	input := &ProjectOverview{
		ShortDescription: "A CLI tool for project memory management.",
		LongDescription:  "TaskWing provides AI assistants with permanent memory about your codebase architecture.",
		GeneratedAt:      now,
	}

	// Save it
	if err := db.SaveProjectOverview(input); err != nil {
		t.Fatalf("SaveProjectOverview failed: %v", err)
	}

	// Retrieve it
	got, err := db.GetProjectOverview()
	if err != nil {
		t.Fatalf("GetProjectOverview failed: %v", err)
	}
	if got == nil {
		t.Fatal("expected overview, got nil")
	}

	// Verify fields
	if got.ShortDescription != input.ShortDescription {
		t.Errorf("ShortDescription = %q, want %q", got.ShortDescription, input.ShortDescription)
	}
	if got.LongDescription != input.LongDescription {
		t.Errorf("LongDescription = %q, want %q", got.LongDescription, input.LongDescription)
	}
	if !got.GeneratedAt.Equal(input.GeneratedAt) {
		t.Errorf("GeneratedAt = %v, want %v", got.GeneratedAt, input.GeneratedAt)
	}
	if !got.LastEditedAt.IsZero() {
		t.Errorf("LastEditedAt should be zero, got %v", got.LastEditedAt)
	}
}

func TestProjectOverview_Update(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Create initial overview
	now := time.Now().UTC().Truncate(time.Second)
	initial := &ProjectOverview{
		ShortDescription: "Initial description.",
		LongDescription:  "Initial long description.",
		GeneratedAt:      now,
	}
	if err := db.SaveProjectOverview(initial); err != nil {
		t.Fatalf("initial SaveProjectOverview failed: %v", err)
	}

	// Update with new content (simulating manual edit)
	editTime := now.Add(time.Hour)
	updated := &ProjectOverview{
		ShortDescription: "Updated description.",
		LongDescription:  "Updated long description with more details.",
		GeneratedAt:      now, // Keep original generation time
		LastEditedAt:     editTime,
	}
	if err := db.SaveProjectOverview(updated); err != nil {
		t.Fatalf("update SaveProjectOverview failed: %v", err)
	}

	// Verify update
	got, err := db.GetProjectOverview()
	if err != nil {
		t.Fatalf("GetProjectOverview failed: %v", err)
	}
	if got.ShortDescription != "Updated description." {
		t.Errorf("ShortDescription not updated: got %q", got.ShortDescription)
	}
	if got.LongDescription != "Updated long description with more details." {
		t.Errorf("LongDescription not updated: got %q", got.LongDescription)
	}
	if !got.LastEditedAt.Equal(editTime) {
		t.Errorf("LastEditedAt = %v, want %v", got.LastEditedAt, editTime)
	}
}

func TestProjectOverview_SaveNilError(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Saving nil should return error
	err = db.SaveProjectOverview(nil)
	if err == nil {
		t.Error("expected error when saving nil overview")
	}
}

func TestProjectOverview_ValidationErrors(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Empty short description should fail
	err = db.SaveProjectOverview(&ProjectOverview{
		ShortDescription: "",
		LongDescription:  "Valid long description.",
	})
	if err == nil {
		t.Error("expected error for empty short description")
	}

	// Empty long description should fail
	err = db.SaveProjectOverview(&ProjectOverview{
		ShortDescription: "Valid short.",
		LongDescription:  "",
	})
	if err == nil {
		t.Error("expected error for empty long description")
	}

	// Whitespace-only descriptions should fail
	err = db.SaveProjectOverview(&ProjectOverview{
		ShortDescription: "   ",
		LongDescription:  "Valid long description.",
	})
	if err == nil {
		t.Error("expected error for whitespace-only short description")
	}
}

func TestProjectOverview_AutoGeneratedAt(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Save with zero GeneratedAt - should be auto-set
	input := &ProjectOverview{
		ShortDescription: "Test project.",
		LongDescription:  "Test description.",
		// GeneratedAt intentionally not set
	}

	before := time.Now().UTC()
	if err := db.SaveProjectOverview(input); err != nil {
		t.Fatalf("SaveProjectOverview failed: %v", err)
	}
	after := time.Now().UTC()

	got, err := db.GetProjectOverview()
	if err != nil {
		t.Fatalf("GetProjectOverview failed: %v", err)
	}

	// GeneratedAt should be set to a time between before and after
	if got.GeneratedAt.Before(before.Add(-time.Second)) || got.GeneratedAt.After(after.Add(time.Second)) {
		t.Errorf("GeneratedAt %v not in expected range [%v, %v]", got.GeneratedAt, before, after)
	}
}

func TestProjectOverview_Repository(t *testing.T) {
	db, err := NewSQLiteStore(":memory:")
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	defer db.Close()

	// Test through Repository layer
	repo := NewRepository(db, nil)

	// Get from empty
	overview, err := repo.GetProjectOverview()
	if err != nil {
		t.Fatalf("repo.GetProjectOverview failed: %v", err)
	}
	if overview != nil {
		t.Error("expected nil overview from empty repo")
	}

	// Save through repo
	input := &ProjectOverview{
		ShortDescription: "Repo test.",
		LongDescription:  "Testing through repository layer.",
		GeneratedAt:      time.Now().UTC(),
	}
	if err := repo.SaveProjectOverview(input); err != nil {
		t.Fatalf("repo.SaveProjectOverview failed: %v", err)
	}

	// Get through repo
	got, err := repo.GetProjectOverview()
	if err != nil {
		t.Fatalf("repo.GetProjectOverview after save failed: %v", err)
	}
	if got == nil {
		t.Fatal("expected overview after save, got nil")
	}
	if got.ShortDescription != input.ShortDescription {
		t.Errorf("ShortDescription = %q, want %q", got.ShortDescription, input.ShortDescription)
	}
}
