# GoReleaser configuration for TaskWing
# Documentation: https://goreleaser.com
version: 2

# Pre-release hooks
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

# Build configuration
builds:
  - id: taskwing
    binary: taskwing
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore: []
    ldflags:
      - -s -w
      - -X github.com/josephgoksu/TaskWing/cmd.version={{.Version}}
      - -X github.com/josephgoksu/TaskWing/cmd.commit={{.Commit}}
      - -X github.com/josephgoksu/TaskWing/cmd.date={{.Date}}

# Archive configuration
archives:
  - id: taskwing-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides: []
    files:
      - README.md
      - LICENSE
      - .taskwing.example.yaml

# Checksums
checksum:
  name_template: "checksums.txt"

# Changelog generation - DISABLED for manual release notes
# The release script (make release) handles manual notes via annotated tags
changelog:
  disable: true

# GitHub release configuration
release:
  github:
    owner: josephgoksu
    name: TaskWing
  draft: false
  prerelease: auto
  mode: replace
  disable: false
  skip_upload: false
  header: |
    ## TaskWing {{.Tag}}

    See release notes below for what's new in this version.

  footer: |
    ---

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew tap josephgoksu/tap
    brew install taskwing
    ```

    **Manual Installation:**
    1. Download the appropriate binary for your platform from the assets below
    2. Extract the archive
    3. Move the binary to a directory in your PATH
    4. Run `taskwing --help` to get started

    **From Source:**
    ```bash
    git clone https://github.com/josephgoksu/TaskWing
    cd TaskWing
    go build -o taskwing main.go
    ```

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser) 🚀

# Homebrew formula
brews:
  - name: taskwing
    description: "AI-Native Task Management - Generate context-aware dev tasks that match your architecture"
    homepage: "https://taskwing.app"
    license: "MIT"
    repository:
      owner: josephgoksu
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "taskwing"
    test: |
      system "#{bin}/taskwing", "version"

# Scoop bucket for Windows removed - focusing on Linux/macOS only

# Docker images (disabled - uncomment when ready)
# dockers:
#   - image_templates:
#     - "josephgoksu/taskwing:latest"
#     - "josephgoksu/taskwing:{{ .Tag }}"
#     - "josephgoksu/taskwing:v{{ .Major }}"
#     dockerfile: Dockerfile
#     build_flag_templates:
#     - "--pull"
#     - "--label=org.opencontainers.image.created={{.Date}}"
#     - "--label=org.opencontainers.image.title={{.ProjectName}}"
#     - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#     - "--label=org.opencontainers.image.version={{.Version}}"
#     skip_push: true

# Snapcraft (disabled - uncomment when ready)
# snapcrafts:
#   - name: taskwing
#     summary: AI-assisted CLI task manager for developers
#     description: |
#       TaskWing is a command-line task management tool designed for developers
#       who want to organize their work efficiently while leveraging AI assistance
#       for better productivity.
#     grade: stable
#     confinement: strict
#     publish: false
#     license: MIT
