# GoReleaser configuration for TaskWing
# Documentation: https://goreleaser.com

# Pre-release hooks
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

# Build configuration
builds:
  - id: taskwing
    binary: taskwing
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/josephgoksu/taskwing.app/cmd.version={{.Version}}
      - -X github.com/josephgoksu/taskwing.app/cmd.commit={{.Commit}}
      - -X github.com/josephgoksu/taskwing.app/cmd.date={{.Date}}

# Archive configuration
archives:
  - id: taskwing-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - MCP_GUIDE.md
      - LICENSE
      - .taskwing.example.yaml

# Checksums
checksum:
  name_template: 'checksums.txt'

# Changelog generation
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Enhancements'
      regexp: '^.*?(enhancement|refactor)(\(.+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# GitHub release configuration
release:
  github:
    owner: josephgoksu
    name: taskwing.app
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## TaskWing {{.Tag}}
    
    ### AI-Assisted CLI Task Manager for Developers
    
    TaskWing helps you manage tasks efficiently with powerful AI integration through the Model Context Protocol (MCP).
    
    ### Quick Start
    
    1. Download the appropriate binary for your platform
    2. Extract the archive
    3. Run `./taskwing init` to initialize TaskWing in your project
    4. Start managing tasks with `./taskwing add`
    
    ### AI Integration
    
    TaskWing supports MCP for seamless AI tool integration:
    ```bash
    # Start MCP server for AI tools
    ./taskwing mcp
    ```
    
    See the included MCP_GUIDE.md for detailed AI integration instructions.
    
  footer: |
    ---
    
    ### Installation
    
    **Homebrew (macOS/Linux):**
    ```bash
    # Coming soon
    ```
    
    **Manual Installation:**
    1. Download the appropriate binary for your platform from the assets below
    2. Extract the archive
    3. Move the binary to a directory in your PATH
    4. Run `taskwing --help` to get started
    
    **From Source:**
    ```bash
    git clone https://github.com/josephgoksu/taskwing.app
    cd taskwing.app
    go build -o taskwing main.go
    ```
    
    ---
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser) 🚀

# Homebrew tap (future)
brews:
  - name: taskwing
    description: "AI-assisted CLI task manager for developers"
    homepage: "https://github.com/josephgoksu/taskwing.app"
    license: "MIT"
    repository:
      owner: josephgoksu
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: true  # Enable when homebrew-tap repo is ready

# Docker images (future)
dockers:
  - image_templates:
    - "josephgoksu/taskwing:latest"
    - "josephgoksu/taskwing:{{ .Tag }}"
    - "josephgoksu/taskwing:v{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: true  # Enable when Docker Hub is ready

# Snapcraft (future)
snapcrafts:
  - name: taskwing
    summary: AI-assisted CLI task manager for developers
    description: |
      TaskWing is a command-line task management tool designed for developers 
      who want to organize their work efficiently while leveraging AI assistance 
      for better productivity.
    grade: stable
    confinement: strict
    publish: false  # Enable when Snapcraft is ready
    license: MIT