# TaskWing Configuration Example
# Copy this to .taskwing.yaml in your project or home directory

project:
  # Base directory for TaskWing files
  rootDir: ".taskwing"

  # Directory for task data (relative to rootDir)
  tasksDir: "tasks"

  # Log file path
  outputLogPath: "logs/taskwing.log"

data:
  # Task data file name
  file: "tasks.json"

  # Data format: json, yaml, or toml
  format: "json"

# Optional: LLM Configuration (for task generation)
# llm:
#   # Default model (used if role-specific not set)
#   provider: "openai"
#   model: "gpt-5-mini"
#
#   # Role-specific models (optional - override default for cost optimization)
#   # Bootstrap uses expensive capable models for deep analysis
#   # Query uses cheap fast models for frequent context lookups
#   models:
#     bootstrap: "openai:gpt-5"           # Used by: tw bootstrap, tw plan
#     query: "gemini:gemini-2.0-flash"    # Used by: tw context, recall MCP
#
#   # API keys can also be set via environment variables:
#   # OPENAI_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY
#   maxOutputTokens: 16384
#   temperature: 0.7

# Optional: Debug settings
debug: false
verbose: false