# TaskWing Configuration Example
# Copy this to .taskwing.yaml in your project or home directory

project:
  # Base directory for TaskWing files
  rootDir: ".taskwing"
  
  # Directory for task data (relative to rootDir)
  tasksDir: "tasks"
  
  # Log file path
  outputLogPath: "logs/taskwing.log"

data:
  # Task data file name
  file: "tasks.json"
  
  # Data format: json, yaml, or toml
  format: "json"

# Optional: LLM Configuration (for task generation)
# llm:
#   provider: "openai"
#   modelName: "gpt-5-mini-2025-08-07"
#   # apiKey: "sk-..." # Set via OPENAI_API_KEY or TASKWING_LLM_APIKEY
#   maxOutputTokens: 16384
#   temperature: 0.7

# Optional: Debug settings
debug: false
verbose: false