package cmd

import (
	"fmt"

	"github.com/josephgoksu/TaskWing/internal/config"
	"github.com/josephgoksu/TaskWing/internal/memory"
	"github.com/spf13/cobra"
)

var taskCmd = &cobra.Command{
	Use:   "task",
	Short: "Manage execution tasks",
	Long:  `View and manage tasks generated by the planning agent.`,
}

var taskListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all tasks",
	RunE: func(cmd *cobra.Command, args []string) error {
		// Use the correct helper from root.go or viper directly
		repo, err := memory.NewDefaultRepository(config.GetMemoryBasePath())
		if err != nil {
			return err
		}
		defer repo.Close()

		// For now, listing plans and their tasks might be better done via plans list
		// but let's implement listing all active tasks?
		// Store API supports ListTasks(planID).
		// We might need ListAllTasks() in store if we want global list.
		// For POC, let's iterate plans.

		plans, err := repo.ListPlans()
		if err != nil {
			return err
		}

		fmt.Println("STATUS\t\tPRIORITY\tTITLE")
		for _, p := range plans {
			tasks, _ := repo.ListTasks(p.ID)
			for _, t := range tasks {
				fmt.Printf("[%s]\t%d\t\t%s\n", t.Status, t.Priority, t.Title)
			}
		}
		return nil
	},
}

var taskValidateCmd = &cobra.Command{
	Use:   "validate [task-id]",
	Short: "Validate a task (Placeholder)",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("🕵️  Validation agent coming in V2.1")
		fmt.Println("    For now, please run the validation steps manually:")

		// Logic to fetch task and print validation steps would go here
	},
}

func init() {
	rootCmd.AddCommand(taskCmd)
	taskCmd.AddCommand(taskListCmd)
	taskCmd.AddCommand(taskValidateCmd)
}
