// TaskWing Plugin for OpenCode
// This plugin integrates TaskWing's autonomous task execution with OpenCode.
// Generated by TaskWing - do not edit manually (will be overwritten on bootstrap).
//
// TASKWING_MANAGED_PLUGIN
// Version: 9784a28ac773

export default async (ctx) => ({
  // session.created: Called when a new OpenCode session starts
  // Equivalent to Claude Code's SessionStart hook
  "session.created": async (event) => {
    try {
      await ctx.$`taskwing hook session-init`;
      ctx.client.app.log("info", "TaskWing session initialized");
    } catch (error) {
      ctx.client.app.log("warn", `TaskWing session-init failed: ${error.message}`);
    }
  },

  // session.idle: Called when the session becomes idle (task completed)
  // Equivalent to Claude Code's Stop hook - checks if should continue to next task
  "session.idle": async (event) => {
    try {
      const result = await ctx.$`taskwing hook continue-check --max-tasks=5 --max-minutes=30`;
      if (result.exitCode === 0 && result.stdout.includes("CONTINUE")) {
        ctx.client.app.log("info", "TaskWing: Continuing to next task");
        // OpenCode will pick up the next task context from stdout
      }
    } catch (error) {
      ctx.client.app.log("debug", `TaskWing continue-check: ${error.message}`);
    }
  },

  // session.compacted: Called when session context is being summarized
  // Can be used to preserve important TaskWing state during compaction
  "session.compacted": async (event) => {
    ctx.client.app.log("debug", "TaskWing: Session compacted");
  }
});
